### ISSUE TITLE
Getting error after payment

### ISSUE THREAD

**Issue by vikasyadav1148** [RazerMS/WordPress_WooCommerce_WP-eCommerce_ClassiPress#19]
After making payment I am getting error on callback 
https://woocommerce-210423-1240615.cloudwaysapps.com/?wc-api=WC_Molpay_Gateway

![image](https://user-images.githubusercontent.com/10350716/79110574-628b0380-7d98-11ea-9b8e-13723382a3c7.png)

**Comment by Kheechieng** [comment]
Kindly advise on the version of plugin that you are using.

**Comment by vikasyadav1148** [comment]
@Kheechieng I am using following version of plugin:

WooCommerce Razer Merchant Services Normal => 3.0.0

WooCommerce => 3.9.3

**Comment by Kheechieng** [comment]
@vikasyadav1148 Kindly make sure that you have only one Razer Merchant Services plugin installed at a time and test with a sandbox account which starts with prefix SB_, you may request for a sandbox account by sending an email to support-sa@razer.com if you have not done so.

**Comment by vikasyadav1148** [comment]
@Kheechieng I have only one Razer Merchant Services plugin installed at a time and I have sandbox account.

Also, How can I test sandbox mode with test credentials. Can you please share test credit card details?

**Comment by Kheechieng** [comment]
@vikasyadav1148 For normal integration there is a popup to auto-populate the credit card numbers in the respective field in the payment page. If you are still not able to return correctly, may give me the transaction ID from your test case, I will check the log.

**Comment by vikasyadav1148** [comment]
@Kheechieng Thanks for your help, here what I am getting after making payment:

Array ( [skey] => 0e71d2f41132114db98c8f81646d50f7 [tranID] => 30152095 [domain] => SB_kensapothecary [status] => 11 [amount] => 986.00 [currency] => MYR [paydate] => 2020-04-13 22:29:55 [orderid] => 34121 [appcode] => [error_code] => CC_14 [error_desc] => Transaction not approved - Invalid account number (no such number) [channel] => Credit )

**Comment by vikasyadav1148** [comment]
@Kheechieng  Also, after making payment successfully it is not going to order-received  page and also it is not reflecting on website can you please tell me how to fix that?

**Comment by Kheechieng** [comment]
@vikasyadav1148 Please make sure the setting below is correct, if you have or have not installed any ordering plugins.
![image](https://user-images.githubusercontent.com/19460508/79133687-05ff0700-7ddf-11ea-9a83-7e6cc42259b6.png)

**Comment by vikasyadav1148** [comment]
@Kheechieng  What is ordering plugin and is it required?

**Comment by Kheechieng** [comment]
@vikasyadav1148 It's a WooCommerce plugin to make sure that your order ID is in sequential order, it is not compulsory, if you have not installed any just make sure you select the right option.

**Comment by vikasyadav1148** [comment]
Ok thanks @Kheechieng 

How to handle the payment response code and show error and also will it automatically redirect to order- received Page after successful payment?

**Comment by Kheechieng** [comment]
@vikasyadav1148 If the order is received it will redirect to below page for example:  
![image](https://user-images.githubusercontent.com/19460508/79134587-8a9e5500-7de0-11ea-96a3-ed703a19eb20.png)

**Comment by vikasyadav1148** [comment]
@Kheechieng  what if any error comes? How to handle that?

**Comment by vikasyadav1148** [comment]
@Kheechieng  In sandbox mode other than "WooCommerce Razer Merchant Services Normal" other plugins like "WooCommerce Razer Merchant Services Seamless for Sequential Order Numbers Pro" are not working as transaction is always is denied is there any limitation in sandbox mode?

**Comment by Kheechieng** [comment]
@vikasyadav1148 Error on which end? If the transaction failed it will be reflected on the parameters. There are dependency for "WooCommerce Razer Merchant Services Seamless for Sequential Order Numbers Pro", you need to install other plugin as mentioned in my previous comment.

**Comment by vikasyadav1148** [comment]
@Kheechieng I have installed all the dependencies but with "WooCommerce Razer Merchant Services Seamless for Sequential Order Numbers Pro" I always gets error message for transction failed with test credentials.

**Comment by Kheechieng** [comment]
@vikasyadav1148 Are you sure you have the right plugin? The pro version is a paid service

**Comment by vikasyadav1148** [comment]
@Kheechieng How I can share the website details to you to verify the details?

**Comment by Kheechieng** [comment]
@vikasyadav1148 I think its better to share in an email instead of publicly in this thread, I will close this issue and you may follow up by sending an email to support-sa@razer.com.
